[package]
name = "htsget-actix"
version = "0.2.0"
rust-version = "1.64"
authors = ["Daniel del Castillo de la Rosa <delcastillodelarosadaniel@gmail.com>", "Marko Malenic <mmalenic1@gmail.com>"]
edition = "2021"
license = "MIT"
description = "This crate is used for running a local (webserver) instance of htsget-rs."
documentation = "https://github.com/umccr/htsget-rs/blob/main/htsget-actix/README.md"
homepage = "https://github.com/umccr/htsget-rs/blob/main/htsget-actix/README.md"
repository = "https://github.com/umccr/htsget-rs"

[features]
s3-storage = ["htsget-config/s3-storage", "htsget-config/s3-storage", "htsget-http/s3-storage", "htsget-test/s3-storage"]
default = ["s3-storage"]

[dependencies]
actix-web = "4.3"
actix-cors = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures-util = { version = "0.3" }
htsget-http = { version = "0.2.0", path = "../htsget-http", default-features = false }
htsget-search = { version = "0.2.0", path = "../htsget-search", default-features = false }
htsget-config = { version = "0.2.0", path = "../htsget-config", default-features = false }
htsget-test = { version = "0.2.0", path = "../htsget-test", features = ["server-tests", "cors-tests"], default-features = false }
futures = { version = "0.3" }
tokio = { version = "1.25", features = ["macros", "rt-multi-thread"] }

tracing-actix-web = "0.7"
tracing = "0.1"

[dev-dependencies]
async-trait = "0.1"

criterion = { version = "0.4", features = ["async_tokio"] }
reqwest = { version = "0.11", default-features = false, features = ["json", "blocking", "rustls-tls"] }
tempfile = "3.3"

[[bench]]
name = "request-benchmarks"
harness = false
path = "benches/request_benchmarks.rs"
